### ISSUE TITLE
head does still not compile on macos 10.5 with gcc4.7

### ISSUE THREAD

**Issue by ClausKlein** [ninja-build/ninja#396]
./ninja all
[2/3 3.4(?)/s] CXX build/build_log_perftest.o
FAILED: /opt/local/libexec/ccache/g++ -MMD -MT build/build_log_perftest.o -MF build/build_log_perftest.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -fvisibility=hidden -pipe '-DNINJA_PYTHON="Python"' -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -Wsign-compare -Wconversion -Wpointer-arith -Wcomment -Wcast-align -Wcast-qual -c src/build_log_perftest.cc -o build/build_log_perftest.o
In file included from src/build_log.h:23:0,
                 from src/build_log_perftest.cc:18:
src/hash_map.h: In function 'unsigned int MurmurHash2(const void_, int)':
src/hash_map.h:29:39: warning: cast from type 'const unsigned char_' to type 'unsigned int*' casts away qualifiers [-Wcast-qual]
src/build_log_perftest.cc: In function 'int main()':
src/build_log_perftest.cc:126:21: warning: conversion to 'float' from 'int' may alter its value [-Wconversion]
src/build_log_perftest.cc:134:39: warning: conversion to 'float' from 'std::__cxx1998::vector<int, std::allocator<int> >::size_type {aka long unsigned int}' may alter its value [-Wconversion]
src/build_log_perftest.cc:136:23: error: 'unlink' was not declared in this scope
ninja: build stopped: subcommand failed.
