### ISSUE TITLE
error: use of undeclared identifier 'O_CLOEXEC'

### ISSUE THREAD

**Issue by ryandesign** [ninja-build/ninja#2645]
Ninja 1.13.1 doesn't build on the elderly Mac OS X 10.6.x or earlier:

```
./src/jobserver-posix.cc:86:66: error: use of undeclared identifier 'O_CLOEXEC'
    read_fd_ = ::open(fifo_path.c_str(), O_RDONLY | O_NONBLOCK | O_CLOEXEC);
                                                                 ^
./src/jobserver-posix.cc:97:67: error: use of undeclared identifier 'O_CLOEXEC'
    write_fd_ = ::open(fifo_path.c_str(), O_WRONLY | O_NONBLOCK | O_CLOEXEC);
                                                                  ^
2 errors generated.
```

Here is a full build log: https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/241480/steps/install-port/logs/stdio

This is a recent regression. Ninja 1.12.1 worked fine.

Thanks to @barracuda156 for alerting me to this.

**Comment by ryandesign** [comment]
One workaround can be:

```c
#ifndef O_CLOEXEC
#define O_CLOEXEC 0
#endif
```

You won't get the functionality of `O_CLOEXEC` but it'll build.

**Comment by jhasse** [comment]
Why would one run macOS 10.6?

**Comment by barracuda156** [comment]
> Why would one run macOS 10.6?

1. Hmm, why not?
2. There is hardware for which this is the latest version.
3. Some important peripherals have drivers only for some OS versions, which restrict choices.
4. MacOS 10.7 has no support for powerpc, so whether one just likes using PowerPC or does that for testing purposes, 10.6 is the last OS that can run. (For example, this allows testing on a Big-endian platform without spending a fortune on an IBM workstation.)

**Comment by digit-google** [comment]
> > Why would one run macOS 10.6?
> 
> 1. Hmm, why not?

The usual reason is because that introduces code that *the upstream team can never test* on newer systems. If it introduces extra coupling or complexity in the code base, this makes things even harder to maintain. E.g. there is a reason why Linux just dropped i386 support entirely. It's always a matter of trade-offs.

> 2. There is hardware for which this is the latest version.

This hardware could use an older version of Ninja too. I didn't realize that 10.6.x dates from 2009 when I wrote the fix.
On the other hand, the fix is entirely self-contained in one source file and would not impact the rest of Ninja.

> 3. Some important peripherals have drivers only for some OS versions, which restrict choices.

I would argue this is not the project maintainer's problem, as using a previous version of Ninja should be largely enough.
And I assume there are many other projects that do not build / compile / run correctly on this machine anyway.

> 4. MacOS 10.7 has no support for powerpc, so whether one just likes using PowerPC or does that for testing purposes, 10.6 is the last OS that can run. (For example, this allows testing on a Big-endian platform without spending a fortune on an IBM workstation.)

Someone using PowerPC is doomed to use ancient versions of most software anyway :-/ Use Ninja 1.12 and most of your current problems will be solved.

**Comment by jhasse** [comment]
I see. Hm ... not really sure if we should include the fix though. We can't provide support for that platform and it's probably safer to use ninja 1.12 as @digit-google said. I would guess that macports has a way to pin a version?

So as with RHEL 7 I have to close this as WONTFIX to reduce maintenance burden on our side. Sorry :/

**Comment by barracuda156** [comment]
@digit-google Dropping every platform besides a few mainstream ones has a cost: only bugs which happen to show up on those gonna be detected and fixed. In effect, such policy de-incentivizes free testing (or at least reporting) which community could have carried out.
Admittedly, this is not uncommon that upstream bugs are being fixed only downstream (in Debian, NetBSD, MacPorts or you name it), but such situation makes everyone in open-source ecosystem worse-off eventually.

> Someone using PowerPC is doomed to use ancient versions of most software anyway :-/ 

P. S. This is certainly false if the stress is on “most”, but I won’t be hugely surprised if some software I have working on my PowerPC is newer than on some current Linux distro or macOS. Moreover, some software will be actually working while being broken on modern macOS, for example.

**Comment by digit-google** [comment]
Small clarification: we can include this specific fix because it is very self-contained and doesn't impact the rest of Ninja. We won't add special code paths to test it works though, and possibilities of bit-rots / the feature not working properly in the future on OS 10.6.x are very real over time.

I was answering the general reason why not to include fixes for really ancient platforms in general, and that at some point the burden of maintaining open-source software for aging systems (released over 15 years ago) should be on the people still using them.

**Comment by barracuda156** [comment]
@digit-google It is a normal practice to have support tiers, like FreeBSD has for archs, for example, and some platforms (whether due to being legacy or simply due to a lack of hardware) may not be tested, and no guarantees provided. IMO, this is to be expected, and de facto the case nearly always.
It is also understandable that even perfectly credible and well-tested patches may not be accepted if they involve hundreds of LoC scattered around the sources.
But in this specific case merging your fix should not be an issue, IMO, which is why it was upsetting to see the PR closed.

P. S. On a general note, it is conceivable that sooner or later a given software will have to be pegged to some version instead of updating. As of now, however – and we talk about a span of 20 years – such cases are relatively uncommon. I mention this just to make it explicit that it is not at all the case that we got all software outdated and randomly insist on having the latest Ninja working. GCC upstream still supports macOS 10.4+ (in practice rather 10.5+, but still, PowerPC included), the latest CMake works, the latest Python and meson work, largely all software – with exception of Qt-based – is in the current releases. I have a lot of ports using C23 and C++23. Users aren’t numerous, I admit, but a lot of modern software works fine (not just builds, but works and passes tests).
