### PR TITLE
Support older systems without O_CLOEXEC

### LINKED ISSUE #2645: error: use of undeclared identifier 'O_CLOEXEC'
Ninja 1.13.1 doesn't build on the elderly Mac OS X 10.6.x or earlier:

```
./src/jobserver-posix.cc:86:66: error: use of undeclared identifier 'O_CLOEXEC'
    read_fd_ = ::open(fifo_path.c_str(), O_RDONLY | O_NONBLOCK | O_CLOEXEC);
                                                                 ^
./src/jobserver-posix.cc:97:67: error: use of undeclared identifier 'O_CLOEXEC'
    write_fd_ = ::open(fifo_path.c_str(), O_WRONLY | O_NONBLOCK | O_CLOEXEC);
                                                                  ^
2 errors generated.
```

Here is a full build log: https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/241480/steps/install-port/logs/stdio

This is a recent regression. Ninja 1.12.1 worked fine.

Thanks to @barracuda156 for alerting me to this.

### PR DESCRIPTION
**Pull request by digit-google**
Fixes #2645

### CODE REVIEW

**Comment by jhasse** [comment]
Hm ... not sure if we should add such workarounds for an outdated OS.

**Comment by jhasse** [comment]
see issue

**Comment by barracuda156** [comment]
This is disappointing to see this being closed. At the very least less testing means more bugs will go undetected – and having a software broken does mean less testing (or less reporting, if you wish: if fixes are not accepted, little point to waste time opening issues at all).
